[theme]
# Primary accent color for interactive elements.
primaryColor = "#0072B1"

# Background color for the main content area.
backgroundColor = "#F5F5F5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text.
textColor = "#333333"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans-serif"
