---
title: "Different Models"
author: "Pedro Sanhueza"
date: "5/24/2021"
output: html_document
---

# Estimated Quadratic
```{r message=FALSE, warning=FALSE}
 ## Simulating Data from a Regression Model
  ## This R-chunk is meant to be played in your R Console.
  ## It allows you to explore how the various elements
  ## of the regression model combine together to "create"
  ## data and then use the data to "re-create" the line.

  set.seed(101) #Allows us to always get the same "random" sample
                #Change to a new number to get a new sample

  n <- 30 #set the sample size

  X_i <- runif(n, 15, 45) 
    #Gives n random values from a uniform distribution between 15 to 45.

  beta0 <- 1 #Our choice for the y-intercept. 

  beta1 <- 1.8 #Our choice for the slope. 
  
  beta2 <- -3 #Our choice for the concavity. 

  sigma <- 200.5 #Our choice for the std. deviation of the error terms.


  epsilon_i <- rnorm(n, 0, sigma) 
    #Gives n random values from a normal distribution with mean = 0, st. dev. = sigma.

  Y_i <- beta0 + beta1*X_i + beta2* X_i ^ 2 + epsilon_i 
    #Create Y using the normal error regression model

  fabData <- data.frame(y=Y_i, x=X_i) 
    #Store the data as data

#  View(fabData) 
  

  #In the real world, we begin with data (like fabData) and try to recover the model that 
  # (we assume) was used to created it.

  fab.lm <- lm(y ~ x + I(x^2), data=fabData) #Fit an estimated regression model to the fabData.

  summary(fab.lm) #Summarize your model. 
  
  # saving regression coefficients
b <- coef(fab.lm)
  
  plot(y ~ x, data=fabData) #Plot the data.

  curve(b[1] + b[2] * x + b[3] * x^2, add = TRUE) #Add the estimated regression line to your plot.


  # Now for something you can't do in real life... but since we created the data...

  abline(beta0, beta1, beta2, lty=2) 
    #Add the true regression line to your plot using a dashed line (lty=2). 

  legend("topleft", legend=c("True Line", "Estimated Line"), lty=c(2,1), bty="n") 
    #Add a legend to your plot specifying which line is which.
```


# Estimated Cubic
```{r message=FALSE, warning=FALSE}

# ----- Class Activity - Different Types of Models May 27th, 2021
## Simulating Data from a Regression Model
## This R-chunk is meant to be played in your R Console.
## It allows you to explore how the various elements
## of the regression model combine together to "create"
## data and then use the data to "re-create" the line.

  set.seed(101) #Allows us to always get the same "random" sample
                #Change to a new number to get a new sample

  n <- 30 #set the sample size

  X_i <- runif(n, -2, 3.5) 
  #Gives n random values from a uniform distribution between 15 to 45.

  beta0 <- 2.7 #Our choice for the y-intercept. 

  beta1 <- -4.8 #Our choice for the slope. 
  
  beta2 <- -2.1 #Our choice for the concavity. 
  
  beta3 <- 1.3 #Our choice for the concavity. 

  sigma <- 0.3 #Our choice for the std. deviation of the error terms.


  epsilon_i <- rnorm(n, 0, sigma) 
  #Gives n random values from a normal distribution with mean = 0, st. dev. = sigma.

    Y_i <- beta0 + beta1 * X_i + beta2 * X_i ^ 2 + beta3* X_i ^ 3 + epsilon_i 
  #Create Y using the normal error regression model
  
  fabData <- data.frame(y=Y_i, x=X_i) 
  #Store the data as data

#  View(fabData) 
  

  #In the real world, we begin with data (like fabData) and try to recover the model that 
  # (we assume) was used to created it.

  fab.lm <- lm(y ~ x + I(x^2) + I(x^3), data=fabData) #Fit an estimated regression model to the fabData.

  summary(fab.lm) #Summarize your model. 
  
  # saving regression coefficients
b <- coef(fab.lm)
  
  plot(y ~ x, data=fabData) #Plot the data.

  curve(b[1] + b[2] * x + b[3] * x^2 + b[4]* x^3, add = TRUE) #Add the estimated regression line to your plot.


  # Now for something you can't do in real life... but since we created the data...

  abline(beta0, beta1, beta2, beta3, lty=2) 
    #Add the true regression line to your plot using a dashed line (lty=2). 

  legend("topleft", legend=c("True Line", "Estimated Line"), lty=c(2,1), bty="n") 
    #Add a legend to your plot specifying which line is which.
```

# Estimated Two-Lines Model
```{r message=FALSE, warning=FALSE}

# ----- Class Activity - Different Types of Models May 27th, 2021
## Simulating Data from a Regression Model
## This R-chunk is meant to be played in your R Console.
## It allows you to explore how the various elements
## of the regression model combine together to "create"
## data and then use the data to "re-create" the line.

  set.seed(101) #Allows us to always get the same "random" sample
                #Change to a new number to get a new sample

  n <- 30 #set the sample size

  X_1i <- runif(n, 30, 50) 
  X_2i <- sample(c(0,1),n,replace = TRUE)
  
  #Gives n random values from a uniform distribution between 15 to 45.

  beta0 <- 10 #Our choice for the y-intercept. 

  beta1 <- 0.9 #Our choice for the slope. 
  
  beta2 <- 72.9 #Our choice for the concavity. 
  
  beta3 <- -0.5 #Our choice for the concavity. 

  sigma <- 0.5 #Our choice for the std. deviation of the error terms.


  epsilon_i <- rnorm(n, 0, sigma) 
  #Gives n random values from a normal distribution with mean = 0, st. dev. = sigma.

    Y_i <- beta0 + beta1 * X_1i + beta2 * X_2i^2 + beta3* X_1i * X_2i + epsilon_i 
  #Create Y using the normal error regression model
  
  fabData <- data.frame(y=Y_i, x=X_1i, x_2 = X_2i) 
  #Store the data as data

#  View(fabData) 
  

  #In the real world, we begin with data (like fabData) and try to recover the model that 
  # (we assume) was used to created it.

  fab.lm <- lm(y ~ x + x + x:x_2, data=fabData) #Fit an estimated regression model to the fabData.

  summary(fab.lm) #Summarize your model. 
  
  # saving regression coefficients
b <- coef(fab.lm)
  
  plot(y ~ x, data=fabData) #Plot the data.

  curve(b[1] + b[2]*x, col="skyblue", lwd=2, add=TRUE)  #baseline (in blue)
  curve((b[1] + b[3]) + (b[2] + b[4])*x, col="orange", lwd=2, add=TRUE) #changed line (in orange)

  curve(b[1] + b[2] * x + b[3] * x^2 + b[4]^3, add = TRUE)
  #Add the estimated regression line to your plot.


  # Now for something you can't do in real life... but since we created the data...

  abline(beta0, beta1, beta2, beta3, lty=2) 
    #Add the true regression line to your plot using a dashed line (lty=2). 

  legend("topleft", legend=c("True Line", "Estimated Line"), lty=c(2,1), bty="n") 
    #Add a legend to your plot specifying which line is which.
```

















